script:
  - gem install bundler
  - bundle install
  - bundle exec jekyll build
  job:
  script:
  - gem install bundler
  - bundle install
  - bundle exec jekyll build
  pages:
  script:
    - gem install bundler
    - bundle install
    - bundle exec jekyll build
    pages:
  script:
    - gem install bundler
    - bundle install
    - bundle exec jekyll build -d public